# version: "3.9"
# services:
#   trade-in:
#     build: ./trade_in
#     ports:
#       - "5400:5400"
#     env_file:
#       - ./trade_in/.env

#   verification:
#     build: ./verification
#     ports:
#       - "5401:5401"
#     env_file:
#       - ./verification/.env

#version: "3.9"
services:
  trade-in:
    build: ./trade_in
    ports:
      - "5400:5400"
    env_file:
      - ./trade_in/.env

  verification:
    build: ./verification
    ports:
      - "5401:5401"
    env_file:
      - ./verification/.env
